[package]
name = "packpal"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
pulldown-cmark = "0.13.0"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
chrono = "0.4.42"
